version: '3'
services:
  nginx:
    build: .
    container_name: basic_auth
    ports: 
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./etc/.htpasswd:/etc/nginx/.htpasswd
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/